apiVersion: batch/v1
kind: Job
metadata:
  name: my-gpu-job
spec:
  template:
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: my-gpu-container             
        image: nvcr.io/nvidia/tensorflow:18.10-py3
        command: ["/bin/bash", "-c", "nvidia-smi; nvcc --version; cd /code-to-run && python code-to-run.py"]
        volumeMounts:
        - name: code-to-run
          mountPath: /code-to-run
        # At least 1 gpu is required
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: code-to-run
        configMap:
          name: code-to-run
      restartPolicy: Never